### ISSUE TITLE
Make a list of missing types

### ISSUE THREAD

**Issue by vudaltsov** [php-extended-type-system/type#10]
Let's analyze Psalm/PHPStan types, see what's missing.

**Comment by vudaltsov** [comment]
Object shapes: https://phpstan.org/writing-php-code/phpdoc-types#object-shapes

**Comment by aivchen** [comment]
conditional return type - https://phpstan.org/writing-php-code/phpdoc-types#conditional-return-types
non-falsy-string - https://phpstan.org/writing-php-code/phpdoc-types#other-advanced-string-types
global constants - https://phpstan.org/writing-php-code/phpdoc-types#global-constants
integer masks - https://phpstan.org/writing-php-code/phpdoc-types#integer-masks
list shapes - https://psalm.dev/docs/annotating_code/type_syntax/array_types/#list-shapes
properties-of - https://psalm.dev/docs/annotating_code/type_syntax/utility_types/#properties-oft
class-string-map - https://psalm.dev/docs/annotating_code/type_syntax/utility_types/#class-string-mapt-of-foo-t

**Comment by vudaltsov** [comment]
Thank you, @aivchen.

And thank you, @the-toster for this table. https://docs.google.com/spreadsheets/d/1dK7zT_lEQSxfU4PK5lKCBcS29roeqCtPumcUKGFuM44/edit#gid=0
