### ISSUE TITLE
Lax factory signatures

### ISSUE THREAD

**Issue by klimick** [php-extended-type-system/type#24]
Should signatures `types::keyOf` and `types::valueOf` be restricted?
Both psalm and phpstan prohibit the usage of `key-of`/`value-of` with non-iterable types (except BackedEnum).

This also applies to `types::intersection`.
Intersections between `string` and `int` types are not possible, but intersections between `object1&object2` or `templateType&object1` are possible.

**Comment by vudaltsov** [comment]
I just realized that this where `TemplateType::$constraint` is very useful! You've probably already told me that...

**Comment by vudaltsov** [comment]
There is a problem with proposed `AliasType` here, because it's an unconstrained black box...

**Comment by vudaltsov** [comment]
It seems to me that this problem cannot be trivially solved in the `type` library, otherwise it will grow into a static analyzer :) We should allow to combine types in any way and analyze them later in a static analyzer.

**Comment by vudaltsov** [comment]
Restricting type construction will also affect reflection that should just reflect what is written, not check, whether it is correct or not.

**Comment by klimick** [comment]
Many was discussed. It issue has no sense anymore.
When I created this issue, I had a different understanding of things.
